servertap-io/servertap

.gitignore, pom.xml, src/main/java/io/servertap/api/v1/ServerApi.java, src/main/java/io/servertap/api/v1/models/Server.java
Title says it all. Tested locally 👍 
Possible todo in the future would be to display 1m, 5m, 15m TPS in an array so we maximize the detail we give the user.
Also, I recommend you take a look at [project lombok](https://projectlombok.org/) as it could help minify this code significantly.
Well done overall!
=> Add TPS + Remove deprecated methods

src/main/java/io/servertap/Constants.java, src/main/java/io/servertap/PluginEntrypoint.java, src/main/java/io/servertap/api/v1/PlayerApi.java
=> Converted inventory to uuids

src/main/java/io/servertap/api/v1/ServerApi.java, src/main/java/io/servertap/api/v1/models/Plugin.java
```
➜  ~ curl localhost:4567/v1/plugins | jq .
[
{
"name": "Vault",
"enabled": true,
"version": "1.7.2-b107"
},
{
"name": "Essentials",
"enabled": true,
"version": "2.17.2.0"
},
{
"name": "ServerTap",
"enabled": true,
"version": "0.0.3-SNAPSHOT"
}
]
```
=> Added version string to plugin model

src/main/java/io/servertap/PluginEntrypoint.java, src/main/java/io/servertap/api/v1/ServerApi.java
Added:
- GET `/server/ops`
- POST `/server/ops`
- DELETE `/server/ops`
=> Feature op

src/main/java/io/servertap/PluginEntrypoint.java, src/main/java/io/servertap/api/v1/ServerApi.java, src/main/java/io/servertap/api/v1/models/Objective.java, src/main/java/io/servertap/api/v1/models/Score.java, src/main/java/io/servertap/api/v1/models/Scoreboard.java
Access objective names and entries with v1/scoreboard. Access details and scores for a specific objective with v1/scoreboard/:name.
=> Added a scoreboard endpoint

src/main/java/io/servertap/PluginEntrypoint.java, src/main/resources/config.yml
=> New config switch for debug logs

src/main/java/io/servertap/Constants.java
=> Fixed error message, to better reflect the issue

README.md
People have been asking about current features so I added this list for quick reference.
=> Added a quick glance list of Endpoints to README

src/main/java/io/servertap/Constants.java, src/main/java/io/servertap/PluginEntrypoint.java, src/main/java/io/servertap/ServerExecCommandSender.java, src/main/java/io/servertap/api/v1/ServerApi.java
This is really a stop-gap solution until a better implementation comes along. This will only return a 200 if the command was executed, it will not return the output of the command as you might see in the console.
=> Feature command exec

README.md, pom.xml, src/main/java/io/servertap/PluginEntrypoint.java, src/main/java/io/servertap/RegisteredWebhook.java, src/main/java/io/servertap/WebhookEventListener.java, src/main/java/io/servertap/api/v1/models/ItemStack.java, src/main/java/io/servertap/api/v1/models/Objective.java, src/main/java/io/servertap/api/v1/models/OfflinePlayer.java, src/main/java/io/servertap/api/v1/models/Player.java, src/main/java/io/servertap/api/v1/models/Score.java, src/main/java/io/servertap/api/v1/models/Scoreboard.java, src/main/java/io/servertap/api/v1/models/ServerBan.java, src/main/java/io/servertap/api/v1/models/Whitelist.java, src/main/java/io/servertap/api/v1/models/events/PlayerChatWebhookEvent.java, src/main/java/io/servertap/api/v1/models/events/PlayerDeathWebhookEvent.java, src/main/java/io/servertap/api/v1/models/events/PlayerJoinWebhookEvent.java, src/main/java/io/servertap/api/v1/models/events/PlayerKickWebhookEvent.java, src/main/java/io/servertap/api/v1/models/events/PlayerQuitWebhookEvent.java, src/main/java/io/servertap/api/v1/models/events/WebhookEvent.java, src/main/java/io/servertap/mojang/api/MojangApiService.java, src/main/java/io/servertap/mojang/api/models/NameChange.java, src/main/java/io/servertap/mojang/api/models/NameHistory.java, src/main/java/io/servertap/mojang/api/models/PlayerInfo.java, src/main/resources/config.yml
Probably easier to look at this one per-commit
=> Code formatting, swagger updates, README updates!

README.md, src/main/java/io/servertap/PluginEntrypoint.java, src/main/resources/config.yml
=> Allow the admin to set allowed CORS origins.

pom.xml, src/main/java/io/servertap/Constants.java, src/main/java/io/servertap/PluginEntrypoint.java, src/main/java/io/servertap/api/v1/PAPIApi.java, src/main/resources/plugin.yml
Closes #74 
cc @Scarsz @c1oneman @koutsie
=> Add support for PlaceholderAPI

README.md, src/main/java/io/servertap/PluginEntrypoint.java, src/main/resources/config.yml
=> Add TLS/SSL support!

src/main/java/io/servertap/api/v1/PlayerApi.java, src/main/java/io/servertap/api/v1/models/Player.java
location, dimension, health, hunger, saturation, gamemode
Example:
```json
[
{
"uuid": "55f584e4-f095-48e0-bb8a-eb5c87ffe494",
"displayName": "phybros",
"address": "localhost",
"port": 59397,
"exhaustion": 3.055,
"exp": 0,
"whitelisted": false,
"banned": false,
"op": false,
"balance": null,
"location": [
134.70895847309555,
63,
148.63685270419884
],
"dimension": "NORMAL",
"health": 20,
"hunger": 20,
"saturation": 17,
"gamemode": "SURVIVAL"
}
]
```
Closes #71 #70
=> feat: add new player attributes

src/main/java/io/servertap/PluginEntrypoint.java, src/main/java/io/servertap/api/v1/ServerApi.java
This PR adds world downloading to servertap. Please version the release, as I don't know the versioning this project uses.
=> Added world downloading

docs/index.md, mkdocs.yml, pom.xml, src/main/java/io/servertap/PluginEntrypoint.java, src/main/java/io/servertap/WebhookEventListener.java, src/main/java/io/servertap/api/v1/PlayerApi.java, src/main/java/io/servertap/api/v1/ServerApi.java, src/main/java/io/servertap/api/v1/websockets/WebsocketHandler.java, src/main/java/io/servertap/mojang/api/MojangApiService.java, src/main/java/io/servertap/utils/GsonJsonMapper.java, src/main/java/io/servertap/utils/GsonSingleton.java, src/main/resources/plugin.yml
Quite a lot of changes to make it work.
Closes #108
=> Upgrade to javalin 4.1.1

README.md
=> Formatted the discord section a bit more nicely.

src/main/java/io/servertap/Constants.java, src/main/java/io/servertap/PluginEntrypoint.java, src/main/java/io/servertap/api/v1/PluginApi.java, src/main/java/io/servertap/api/v1/ServerApi.java, src/main/java/io/servertap/api/v1/models/Plugin.java
Also
- move plugins to PluginApi
- add some new fields to the Plugin model
=> Add Plugin download+install

src/main/java/io/servertap/WebhookEventListener.java, src/main/java/io/servertap/api/v1/models/events/PlayerChatWebhookEvent.java
Add Player in PlayerChatWebhookEvent from AsyncPlayerChatEvent when onPlayerChat to webhook。
I need it to know who are chat by uid
=> Add Player in PlayerChatWebhookEvent from AsyncPlayerChatEvent when onPlayerChat to webhook

.github/workflows/build.yml, CHANGELOG.md, README.md, docs/index.md, pom.xml, src/main/java/io/servertap/PluginEntrypoint.java, src/main/java/io/servertap/api/v1/EconomyApi.java, src/main/java/io/servertap/api/v1/PAPIApi.java, src/main/java/io/servertap/api/v1/PlayerApi.java, src/main/java/io/servertap/api/v1/PluginApi.java, src/main/java/io/servertap/api/v1/ServerApi.java, src/main/java/io/servertap/api/v1/WorldApi.java, src/main/java/io/servertap/api/v1/models/Player.java, src/main/java/io/servertap/api/v1/models/World.java, src/main/java/io/servertap/api/v1/websockets/WebsocketHandler.java, src/main/java/io/servertap/utils/GsonJsonMapper.java, src/main/resources/config.yml, src/main/resources/plugin.yml
=> update to java 19 and javalin 5

pom.xml
Tested built jar with java 17, 18, 19, 20 all good
=> make the jar compatible down to java 17

pom.xml, src/main/java/io/servertap/api/v1/PlayerApi.java
Code fix was required to upgrade the nbt api library
=> Phybros/nbt upgrade 2.11.2

src/main/java/io/servertap/api/v1/ServerApi.java
Fixed the scoreboard issue reported in this [support ticket](https://discord.com/channels/919982507271802890/1191801349629820998).
=> Fixed scoreboard code!

src/main/java/io/servertap/api/v1/ServerApi.java
Whitelist would be displayed as turned off when it was actually enabled
=> Whitelist enabled check inverted

pom.xml, src/main/java/io/servertap/api/v1/ServerApi.java, src/test/java/io/servertap/TestPluginClass.java
Updating dependencies, and adding error handling to failed scoreboard loading seemed to fix the issue.
=> Fix scoreboard failure to initialize
